{
 "title": "eBPF Programs Performance",
 "tags": [
  "ebpf",
  "cpu"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "eBPF Program CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(ebpf_run_time{ebpf_name!=\"\"}[1m]) * 1000",
     "legendFormat": "Name: {{ebpf_name}}, ID: {{ebpf_id}}"
    },
    {
     "expr": "sum(irate(ebpf_run_time{ebpf_name!=\"\"}[1m]) * 1000)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "eBPF events/sec",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "irate(ebpf_event_count{ebpf_name!=\"\"}[1m])",
     "legendFormat": "Name: {{ebpf_name}}, ID: {{ebpf_id}}"
    },
    {
     "expr": "sum(irate(ebpf_event_count{ebpf_name!=\"\"}[1m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "eBPF map pressure",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "ebpf_map_size{ebpf_map_max_size!=\"1\"}",
     "legendFormat": "Name: {{ebpf_map_name}}, ID: {{ebpf_map_id}}"
    }
   ]
  }
 ]
}